[project]
name = "google-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "playwright>=1.58.0",
    "selenium>=4.41.0",
    "typer>=0.24.1",
]
